library("WindResource")
data(wd)

runGUI(wd)

# Histogram
plotWD (data=wd, var="speed", type="histogram", by="none")
plotWD (data=wd, var="speed", type="histogram", by="month")
plotWD (data=wd, var="speed", type="histogram", by="hour")

tableWD(data=wd,var="speed", type="histogram", by="none")
table.wd (data=wd,var="speed", type="histogram", by="month")
table.wd (data=wd,var="speed", type="histogram", by="hour")

plotWD (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="rose", by="none")
plotWD (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="rose", by="month")
plotWD (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="rose", by="hour")
plotWD (data=wd,var="speed", type="rose", by="none")
plotWD (data=wd,var="speed", type="rose", by="month")
plotWD (data=wd,var="speed", type="rose", by="hour")
plotWD (data=wd,var="speed", type="correlation", by="hour")
plotWD (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="profile", by="month")
plotWD (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="profile", by="hour")
plotWD (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="profile", by="hour",since="2013-02-01",to="2013-02-28")
plotWD (data=wd,var="speed", type="sdfsf", by="hour")
table.wd (data=wd, ane=NA, var=c("speed"),  type=c("rose"), by=c("month"))

table.wd (data=wd,var="speed", type="histogram", by="none")
table.wd (data=wd,var="speed", type="histogram", by="month")
table.wd (data=wd,var="speed", type="histogram", by="hour")
table.wd (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="rose", by="none")
table.wd (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="rose", by="month")
table.wd (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="rose", by="hour")
table.wd (data=wd,var="speed", type="rose", by="none")
table.wd (data=wd,var="speed", type="rose", by="month")
table.wd (data=wd,var="speed", type="rose", by="hour")
table.wd (data=wd,var="speed", type="correlation", by="hour")
table.wd (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="profile", by="month")
table.wd (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="profile", by="hour")
table.wd (data=wd,ane=c("Ane1", "Ane2"),var="speed", type="profile", by="hour",since="2013-02-01",to="2013-02-28")
table.wd (data=wd,var="speed", type="sdfsf", by="hour")
table.wd (data=wd, ane=NA, var=c("speed"),  type=c("rose"), by=c("month"))

turbulence (wd)
turbulence (wd10)
